ansible_user: < >
ansible_ssh_pass: < >

host_domain: < >
host_ip: < >

ports: < >
  main_ssh_port: < >
    port: < >
    proto: < >
  https: < >
    port: < >
    proto: < >
  http: < >
    port: < >
    proto: < >
  db_port: < >
    port: < >
    proto: < >

server_groups: < >





main_user: < >
user_password: < >
main_user_ssh_key: < >



db_version: < >
db_user: < >
db_name: < >
db_password: < >
allowed_db_ip: < >
