---
# tasks file for base-tools
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 360

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - sudo
      - fail2ban
      - nano
      - tree
    state: present

- name: Ensure python3 and pip3 are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present




